---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy2-nginx
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: deploy2-nginx
      env: dev
  replicas: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: deploy2-nginx
        env: dev
    spec:
      containers:
      - image: nginx
        imagePullPolicy: Always
        name: nginx
        ports:
        - name: http
          containerPort: 80
      
---
