apiVersion: v1
kind: Service
metadata:
  name: lb-svc-ip-node
  namespace: default
  labels:
    app: lb-svc-ip-node
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: lb-svc-ip-node
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: default
  labels:
    app: lb-svc-ip-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-svc-ip-node
  template:
    metadata:
      labels:
        app: lb-svc-ip-node
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
