apiVersion: v1
kind: Pod
metadata:
  name: service-discovery
spec:
  dnsPolicy: Default # "Default" is not the true default value
  enableServiceLinks: false
  containers:
  - name: privileged-container
    image: ubuntu
    resources:
      requests:
        cpu: "0.2"
        memory: "256Mi"
      limits:
        cpu: "1"
        memory: "1Gi"    
    command: ["/bin/bash"]
    args: ["-c", "echo 'This is a privileged pod'"]
