apiVersion: v1
kind: Service
metadata:
  name: lb-svc-ip-node
  namespace: lb
  labels:
    app: lb-svc-ip-node
  annotations:
     service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
     service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
     service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: lb-svc-ip-node
---
