---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  namespace: lb
  labels:
    app: lb-svc-ip-node
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lb-svc-ip-node
  template:
    metadata:
      labels:
        app: lb-svc-ip-node
    spec:
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
              protocol: TCP
