---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: pdb-deploy1-nginx
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: deploy1-nginx
      env: dev      
---
