apiVersion: apps/v1
kind: Deployment
metadata:
  name: readiness
  labels:
    app: web-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web-server
  template:
    metadata:
      labels:
        app: web-server
    spec:
      containers:
      - name: web-app
        image: nginx:1.16-alpine
        resources:
          requests:
            cpu: "0.2"
            memory: "256Mi"
          limits:
            cpu: "1"
            memory: "1Gi"          
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10        
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5