---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test
spec:
  secretName: test-cert-tls
  dnsNames:
    - test.cloudtechconsulting.in
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
