---
apiVersion: v1
kind: Pod
metadata:
  name: efs-example2
spec:
  automountServiceAccountToken: false
  containers:
    - name: app
      image: centos
      resources:
        requests:
          cpu: "0.2"
          memory: "256Mi"
        limits:
          cpu: "1"
          memory: "1Gi"      
      command: ["/bin/sh"]
      args: ["-c", "while true; cat /example/out.txt; sleep 5; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /example
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: efs-storage-claim-shared     
