---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pvc-shared
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc2
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d8e0b886dfb5c77a::fsap-0a3e1af5b22ae20a5

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-storage-claim-shared
  namespace: storage
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: efs-sc2
  resources:
    requests:
      storage: 5Gi
