---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pvc1
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  mountOptions:
    - tls  
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-0d8e0b886dfb5c77a

